### ISSUE TITLE
json error in faxFile call

### ISSUE THREAD

**Issue by livyfu** [jfialkoff/pyphaxio#3]
Not sure if it's because of requests lib, phaxio api, pyphaxio, or my own data/environment. Tried under both py2 and py3 and here are the trace backs.

In Python 3 env:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files\Python35\lib\site-packages\phaxio\utils.py", line 3, in _curried
    return _curried_func(*(args+moreargs), **dict(kwargs, **morekwargs))
  File "c:\Program Files\Python35\lib\site-packages\phaxio\api.py", line 98, in _get
    return self.parse_response(r)
  File "c:\Program Files\Python35\lib\site-packages\phaxio\api.py", line 48, in parse_response
    payload = response.json()
  File "c:\Program Files\Python35\lib\site-packages\requests\models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\Program Files\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "c:\Program Files\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Program Files\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In Python2.7 env:

Traceback (most recent call last):
  File "phaxio\utils.pyc", line 3, in _curried
  File "phaxio\api.pyc", line 98, in _get
  File "phaxio\api.pyc", line 48, in parse_response
  File "requests\models.pyc", line 819, in json
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

**Comment by FabioFleitas** [comment]
@livyfu Thanks for submitting this issue. I'll look into this later today and get back to you if I have any further questions.

**Comment by FabioFleitas** [comment]
Hi @livyfu I went ahead and fixed this issue with PR #4. I have updated the version to `0.11` and updated it in PyPI. Let me know if it all works for you now :)

**Comment by livyfu** [comment]
Awesome! @FabioFleitas It works like a charm now. Thanks a lot!

**Comment by FabioFleitas** [comment]
No problem. Going to go ahead and close this issue, but if anything else comes up, feel free to create a new one :)
